name: sonar_assistant
description: "assistant app witch sonar api key"
version: 1.0.0+1

environment:
  sdk: ^3.9.0


dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  retrofit: ^4.7.2
  json_annotation: ^4.9.0
  dio: ^5.9.0
  freezed_annotation: ^3.1.0
  auto_route: ^10.1.2
  web_socket_channel: ^3.0.3


  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^10.0.2
  build_runner: ^2.7.0 
  json_serializable: ^6.11.0
  freezed: ^3.2.0
  auto_route_generator: ^10.2.4 

  flutter_lints: ^6.0.0



flutter:
  uses-material-design: true

assets:
  - assets/fonts/

fonts:
  - family: OpenSans
    fonts:
      - asset: assets/fonts/OpenSans-Regular.ttf
        weight: 400
      - asset: assets/fonts/OpenSans-Bold.ttf
        weight: 700